-- 邮寄取件预约两张新表。纯新增，回滚代码不需要回滚库。
CREATE TABLE `express_bookings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `order_no` VARCHAR(32) NOT NULL,
  `booking_no` VARCHAR(32) NOT NULL,
  `active_order_id` INT NULL,
  `kuaidicom` VARCHAR(32) NOT NULL,
  `service_type` VARCHAR(32) NULL,
  `status` VARCHAR(16) NOT NULL,
  `status_rank` INT NOT NULL DEFAULT 0,
  `provider_status` INT NULL,
  `status_desc` VARCHAR(255) NULL,
  `task_id` VARCHAR(64) NULL,
  `kd_order_id` VARCHAR(64) NULL,
  `kuaidinum` VARCHAR(64) NULL,
  `poll_token` VARCHAR(64) NULL,
  `day_type` VARCHAR(8) NULL,
  `pickup_date` VARCHAR(10) NULL,
  `pickup_start` VARCHAR(5) NULL,
  `pickup_end` VARCHAR(5) NULL,
  `weight_g` INT NOT NULL,
  `customer_fee_fen` INT NOT NULL,
  `quoted_fee_fen` INT NULL,
  `prepaid_fee_fen` INT NULL,
  `settled_fee_fen` INT NULL,
  `billed_weight_g` INT NULL,
  `fee_details` JSON NULL,
  `courier_name` VARCHAR(64) NULL,
  `courier_mobile` VARCHAR(20) NULL,
  `callback_salt` VARCHAR(40) NOT NULL,
  `remark` VARCHAR(64) NULL,
  `error_code` VARCHAR(16) NULL,
  `fail_reason` VARCHAR(255) NULL,
  `cancelled_by` VARCHAR(8) NULL,
  `cancel_reason` VARCHAR(255) NULL,
  `track_json` JSON NULL,
  `track_status` VARCHAR(16) NULL,
  `track_updated_at` DATETIME(3) NULL,
  `booked_at` DATETIME(3) NULL,
  `accepted_at` DATETIME(3) NULL,
  `picked_at` DATETIME(3) NULL,
  `delivered_at` DATETIME(3) NULL,
  `cancelled_at` DATETIME(3) NULL,
  `last_callback_at` DATETIME(3) NULL,
  `unaccepted_reminded_at` DATETIME(3) NULL,
  `unpicked_reminded_at` DATETIME(3) NULL,
  `unknown_reminded_at` DATETIME(3) NULL,
  `cost_alerted_at` DATETIME(3) NULL,
  `reconcile_tries` INT NOT NULL DEFAULT 0,
  `operator` VARCHAR(64) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  UNIQUE INDEX `express_bookings_booking_no_key`(`booking_no`),
  UNIQUE INDEX `express_bookings_active_order_id_key`(`active_order_id`),
  UNIQUE INDEX `express_bookings_task_id_key`(`task_id`),
  INDEX `express_bookings_order_id_idx`(`order_id`),
  INDEX `express_bookings_status_booked_at_idx`(`status`, `booked_at`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `express_booking_events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `booking_id` INT NOT NULL,
  `dedupe_key` VARCHAR(64) NOT NULL,
  `source` VARCHAR(16) NOT NULL,
  `provider_status` INT NULL,
  `status_desc` VARCHAR(255) NULL,
  `courier_name` VARCHAR(64) NULL,
  `courier_mobile` VARCHAR(20) NULL,
  `operator` VARCHAR(64) NULL,
  `raw_payload` JSON NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `express_booking_events_dedupe_key_key`(`dedupe_key`),
  INDEX `express_booking_events_booking_id_created_at_idx`(`booking_id`, `created_at`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `express_bookings` ADD CONSTRAINT `express_bookings_order_id_fkey` FOREIGN KEY (`order_id`) REFERENCES `orders`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `express_booking_events` ADD CONSTRAINT `express_booking_events_booking_id_fkey` FOREIGN KEY (`booking_id`) REFERENCES `express_bookings`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
